# Generated by Django 6.0.6 on 2026-07-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_customer_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada'), ('ANULADA', 'Anulada')], default='PENDIENTE', max_length=15, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Número de Factura'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Saldo'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tipo_pago',
            field=models.CharField(choices=[('CONTADO', 'Contado'), ('CREDITO', 'Crédito')], default='CREDITO', max_length=10, verbose_name='Tipo de Pago'),
        ),
    ]
