# Generated by Django 6.0.6 on 2026-07-13 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_invoice_estado_invoice_numero_invoice_saldo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('PAYPAL', 'PayPal'), ('CREDITO', 'Crédito')], default='EFECTIVO', max_length=20, verbose_name='Método de Pago'),
        ),
    ]
