# Generated by Django 6.0.6 on 2026-07-14 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_invoice_metodo_pago'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name'], 'permissions': [('download_brand_pdf', 'Can download Brand PDF report'), ('download_brand_excel', 'Can download Brand Excel report')], 'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['last_name', 'first_name'], 'permissions': [('download_customer_pdf', 'Can download Customer PDF report'), ('download_customer_excel', 'Can download Customer Excel report')]},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-invoice_date'], 'permissions': [('download_invoice_pdf', 'Can download Invoice PDF report'), ('download_invoice_excel', 'Can download Invoice Excel report')]},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'permissions': [('download_product_pdf', 'Can download Product PDF report'), ('download_product_excel', 'Can download Product Excel report')], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productgroup',
            options={'ordering': ['name'], 'permissions': [('download_productgroup_pdf', 'Can download ProductGroup PDF report'), ('download_productgroup_excel', 'Can download ProductGroup Excel report')], 'verbose_name': 'Product Group', 'verbose_name_plural': 'Product Groups'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name'], 'permissions': [('download_supplier_pdf', 'Can download Supplier PDF report'), ('download_supplier_excel', 'Can download Supplier Excel report')], 'verbose_name': 'Supplier', 'verbose_name_plural': 'Suppliers'},
        ),
    ]
