# Generated by Django 6.0.6 on 2026-07-14 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_alter_brand_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name'], 'permissions': [('download_brand_pdf', 'Can download Brand PDF report'), ('download_brand_excel', 'Can download Brand Excel report'), ('detail_brand', 'Can view Brand detail modal')], 'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['last_name', 'first_name'], 'permissions': [('download_customer_pdf', 'Can download Customer PDF report'), ('download_customer_excel', 'Can download Customer Excel report'), ('detail_customer', 'Can view Customer detail modal')]},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-invoice_date'], 'permissions': [('download_invoice_pdf', 'Can download Invoice PDF report'), ('download_invoice_excel', 'Can download Invoice Excel report'), ('detail_invoice', 'Can view Invoice detail page')]},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'permissions': [('download_product_pdf', 'Can download Product PDF report'), ('download_product_excel', 'Can download Product Excel report'), ('detail_product', 'Can view Product detail modal')], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productgroup',
            options={'ordering': ['name'], 'permissions': [('download_productgroup_pdf', 'Can download ProductGroup PDF report'), ('download_productgroup_excel', 'Can download ProductGroup Excel report'), ('detail_productgroup', 'Can view ProductGroup detail modal')], 'verbose_name': 'Product Group', 'verbose_name_plural': 'Product Groups'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name'], 'permissions': [('download_supplier_pdf', 'Can download Supplier PDF report'), ('download_supplier_excel', 'Can download Supplier Excel report'), ('detail_supplier', 'Can view Supplier detail modal')], 'verbose_name': 'Supplier', 'verbose_name_plural': 'Suppliers'},
        ),
    ]
