# Generated by Django 6.0.6 on 2026-07-16 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_alter_brand_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='clave_acceso',
            field=models.CharField(blank=True, max_length=49, null=True, unique=True, verbose_name='Clave de Acceso SRI'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='estado_sri',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('AUTORIZADO', 'Autorizado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20, verbose_name='Estado SRI'),
        ),
    ]
