# Generated by Django 6.0.6 on 2026-07-19 19:06

import django.db.models.deletion
import shared.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_invoice_clave_acceso_invoice_estado_sri'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=13, unique=True, validators=[shared.validators.validate_cedula_ec], verbose_name='RUC')),
                ('razon_social', models.CharField(max_length=300, verbose_name='Razón Social')),
                ('nombre_comercial', models.CharField(max_length=300, verbose_name='Nombre Comercial')),
                ('dir_matriz', models.CharField(max_length=300, verbose_name='Dirección Matriz')),
                ('dir_establecimiento', models.CharField(max_length=300, verbose_name='Dirección Establecimiento')),
                ('obligado_contabilidad', models.BooleanField(default=False, verbose_name='Obligado a llevar Contabilidad')),
                ('codigo_establecimiento', models.CharField(default='001', max_length=3, verbose_name='Código Establecimiento')),
                ('codigo_punto_emision', models.CharField(default='001', max_length=3, verbose_name='Punto de Emisión')),
                ('secuencial_factura', models.IntegerField(default=1, verbose_name='Siguiente Secuencial de Factura')),
                ('firma_archivo', models.FileField(blank=True, null=True, upload_to='firmas_sri/', verbose_name='Archivo de Firma (.p12)')),
                ('firma_password_encrypted', models.CharField(blank=True, max_length=500, null=True, verbose_name='Contraseña Cifrada')),
                ('ambiente', models.CharField(choices=[('1', 'Pruebas'), ('2', 'Producción')], default='1', max_length=1, verbose_name='Ambiente SRI')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuarios', models.ManyToManyField(blank=True, related_name='empresas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['razon_social'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='billing.empresa'),
        ),
    ]
