# Generated by Django 6.0.6 on 2026-07-20 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_empresa_invoice_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='firma_archivo',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='firma_password_encrypted',
        ),
    ]
