# Generated by Django 6.0.6 on 2026-07-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobrofactura',
            name='fecha',
            field=models.DateTimeField(verbose_name='Fecha/Hora de Cobro'),
        ),
    ]
