# Generated by Django 6.0.6 on 2026-07-14 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0003_pagocompra'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cobrofactura',
            options={'ordering': ['-fecha', '-id'], 'permissions': [('download_cobrofactura_pdf', 'Can download CobroFactura PDF report'), ('download_cobrofactura_excel', 'Can download CobroFactura Excel report'), ('detail_cobrofactura', 'Can view CobroFactura details')], 'verbose_name': 'Cobro de Factura', 'verbose_name_plural': 'Cobros de Facturas'},
        ),
        migrations.AlterModelOptions(
            name='pagocompra',
            options={'ordering': ['-fecha', '-id'], 'permissions': [('download_pagocompra_pdf', 'Can download PagoCompra PDF report'), ('download_pagocompra_excel', 'Can download PagoCompra Excel report'), ('detail_pagocompra', 'Can view PagoCompra details')], 'verbose_name': 'Pago de Compra', 'verbose_name_plural': 'Pagos de Compras'},
        ),
    ]
