# Generated by Django 6.0.6 on 2026-07-17 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RRHH', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='sobretiempo',
            constraint=models.UniqueConstraint(fields=('empleado', 'fecha_registro'), name='unique_sobretiempo_empleado_fecha'),
        ),
    ]
