# Generated by Django 6.0.6 on 2026-07-20 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RRHH', '0002_sobretiempo_unique_sobretiempo_empleado_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPrestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('tasa_interes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interes', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('monto_pagar', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('numero_cuotas', models.PositiveIntegerField(default=1)),
                ('saldo', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('estado', models.CharField(choices=[('PEND', 'Pendiente'), ('PAG', 'Pagado'), ('ANU', 'Anulado')], default='PEND', max_length=4)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RRHH.empleado')),
                ('tipo_prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RRHH.tipoprestamo')),
            ],
        ),
        migrations.CreateModel(
            name='PrestamoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuota', models.PositiveIntegerField()),
                ('fecha_vencimiento', models.DateField()),
                ('valor_cuota', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_cuota', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='RRHH.prestamo')),
            ],
            options={
                'ordering': ['numero_cuota'],
            },
        ),
    ]
