# Generated by Django 6.0.6 on 2026-07-14 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0003_purchase_estado_purchase_saldo_purchase_tipo_pago'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-purchase_date'], 'permissions': [('download_purchase_pdf', 'Can download Purchase PDF report'), ('download_purchase_excel', 'Can download Purchase Excel report')], 'verbose_name': 'Purchase', 'verbose_name_plural': 'Purchases'},
        ),
    ]
