# Generated by Django 6.0.6 on 2026-07-14 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0004_alter_purchase_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-purchase_date'], 'permissions': [('download_purchase_pdf', 'Can download Purchase PDF report'), ('download_purchase_excel', 'Can download Purchase Excel report'), ('detail_purchase', 'Can view Purchase detail page')], 'verbose_name': 'Purchase', 'verbose_name_plural': 'Purchases'},
        ),
    ]
