# Generated by Django 6.0.6 on 2026-07-14 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0005_alter_purchase_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-purchase_date'], 'permissions': [('download_purchase_pdf', 'Can download Purchase PDF report'), ('download_purchase_excel', 'Can download Purchase Excel report'), ('detail_purchase', 'Can view Purchase detail page'), ('whatsapp_purchase', 'Can send Purchase via WhatsApp')], 'verbose_name': 'Purchase', 'verbose_name_plural': 'Purchases'},
        ),
    ]
